<a href="https://colab.research.google.com/github/ariodotpermadi/AspDotNet/blob/master/Tensor_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np


In [13]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

#add short hand
tensor_a + tensor_b

#substraction short hand
tensor_a - tensor_b

#multiple short hand
tensor_a * tensor_b

#Divide short hand
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [6]:
#add function
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [9]:
#subs function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [12]:
#multiple function
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [14]:
#Divide function
torch.div(tensor_a, tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])